_commit: e243060
_src_path: gh:adrn-blog/template
day: 23
month: 9
python_version: '3.12'
slug: fisher-information-toy
title: Some toy examples and pitfalls of the Fisher information matrix
year: 2024
